eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}
