eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://serviceregistry:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}    
spring:
  sleuth:
      enabled: true
  zipkin:
      enabled: true
      base-url: ${ZIPKIN_SERVER:http://zipkin:9411/}
