eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${HOSTNAME:localhost}
